services:
  spotisafe:
    image: ghcr.io/asierzunzu/spotisafe:latest
#    build: .
    ports:
      - "8888:8888"       # Only needed for first-run OAuth callback
    volumes:
      - ./output:/output  # Backup output + token file persistence
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_PUBLIC_URL=${SPOTIFY_PUBLIC_URL}
      - SPOTIFY_OUTPUT_DIR=/output
      - SPOTIFY_TOKEN_FILE=/output/.spotify_token.json
      - SPOTIFY_SCHEDULE=0 2 * * *
      - SPOTIFY_SKIP_INITIAL_RUN=false
      - LOG_LEVEL=info
    restart: unless-stopped
